### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by jonathanbeber** [soldair/node-s3-npm#5]
Hi,

When an error log is thrown isn't good exit with zero. My deploy script fails but there's no way to know without check manually.

What do you think about check if log level is equals error and so process exit with 1?

Thanks.

**Comment by soldair** [comment]
hmm. im not sure i understand completely. would you tell me how you are using it?
do you mean the process is not exiting correctly on install failure? so your deploy looks like it succeeds but actually fails?

**Comment by jonathanbeber** [comment]
No, I'm using `s3npm publish`, if some error occurs the exit code is 0. 

[Here](https://github.com/soldair/node-s3-npm/blob/master/index.js#L32), for example, instead of just log error, I think that should have a `process.exit(1);` also.

May be there's a better solution, but there's a lot of places that it's better exit the process with a value different of zero.

**Comment by soldair** [comment]
Oh yeah. Please send a pull request :)

**Comment by jonathanbeber** [comment]
@soldair okay, I'm gonna try, I'm not a JS developer.

@tortoyoyo Can you help me to code the best way to do that?

**Comment by soldair** [comment]
this is some pretty old code =(
it's also using unsupported npm apis. I have to tell you i can't recommend using this without some updates. And its not because i work at npm now =). I'm going to add this to the readme.

that being said it should work for you.
I'll add the proper process exits in commands publish and install so you can play with this more.

**Comment by jonathanbeber** [comment]
Oh, okay, thanks for help.
